# -*- coding: utf-8 -*-
"""Module7_Customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmRYnFvgTEL2PXDwJtfqHUHZQj7sDRhp
"""

#For data
import numpy as np
import pandas as pd

#For Charts
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

#Preprocessing
from sklearn.preprocessing import OneHotEncoder, LabelEncoder,PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

df = pd.read_csv("/content/customer_segmentation.csv")
df.head()

df = df.copy()
df['Age'] = 2025 - df['Year_Birth']
df['TotalChildren'] = df['Kidhome'] + df['Teenhome']
df['TotalSpent'] = df[['MntWines', 'MntFruits', 'MntMeatProducts',
                       'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']].sum(axis=1)

df_cluster = df[['Income', 'Age', 'TotalChildren', 'Recency', 'TotalSpent']].dropna()
df_cluster

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_cluster)

#1. Find Customer segments using K-means clustering algorithm.
inertia = []
sil_scores = []
K = range(2, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)
    sil_scores.append(silhouette_score(X_scaled, kmeans.labels_))

# Plot elbow + silhouette
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(K, inertia, 'bo-')
plt.title('K-Means Elbow Curve')
plt.xlabel('k'), plt.ylabel('Inertia')

plt.subplot(1, 2, 2)
plt.plot(K, sil_scores, 'go-')
plt.title('Silhouette Score')
plt.xlabel('k'), plt.ylabel('Score')
plt.tight_layout()
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
df_cluster['KMeans_Cluster'] = kmeans.fit_predict(X_scaled)

# 2. Find Customer segments using Hierarchical clustering algorithm.
linked = linkage(X_scaled, method='ward')
plt.figure(figsize=(10, 5))
dendrogram(linked, truncate_mode='lastp', p=10)
plt.title("Dendrogram")
plt.xlabel("Samples")
plt.ylabel("Distance")
plt.show()

df_cluster['Hierarchical_Cluster'] = fcluster(linked, t=4, criterion='maxclust')

#3. Compare the Clusters and conclude your analysis.
print(df_cluster[['KMeans_Cluster','Hierarchical_Cluster']].value_counts())

